import { Card, TypeCard } from "./types";

// 36 - հատ քարտերը
export const cards: Array<Card> = [
  {
    id: 1,
    rank: 6,
    type: TypeCard.diamonds,
    img: "assets/cards/diamonds_6.svg",
  },
  {
    id: 2,
    rank: 6,
    type: TypeCard.hearth,
    img: "assets/cards/hearts_6.svg",
  },
  {
    id: 3,
    rank: 6,
    type: TypeCard.clubs,
    img: "assets/cards/clubs_6.svg",
  },
  {
    id: 4,
    rank: 6,
    type: TypeCard.spades,
    img: "assets/cards/spades_6.svg",
  },
  {
    id: 5,
    rank: 7,
    type: TypeCard.diamonds,
    img: "assets/cards/diamonds_7.svg",
  },
  {
    id: 6,
    rank: 7,
    type: TypeCard.hearth,
    img: "assets/cards/hearts_7.svg",
  },
  {
    id: 7,
    rank: 7,
    type: TypeCard.clubs,
    img: "assets/cards/clubs_7.svg",
  },
  {
    id: 8,
    rank: 7,
    type: TypeCard.spades,
    img: "assets/cards/spades_7.svg",
  },
  {
    id: 9,
    rank: 8,
    type: TypeCard.diamonds,
    img: "assets/cards/diamonds_8.svg",
  },
  {
    id: 10,
    rank: 8,
    type: TypeCard.hearth,
    img: "assets/cards/hearts_8.svg",
  },
  {
    id: 11,
    rank: 8,
    type: TypeCard.clubs,
    img: "assets/cards/clubs_8.svg",
  },
  {
    id: 12,
    rank: 8,
    type: TypeCard.spades,
    img: "assets/cards/spades_8.svg",
  },
  {
    id: 13,
    rank: 9,
    type: TypeCard.diamonds,
    img: "assets/cards/diamonds_9.svg",
  },
  {
    id: 14,
    rank: 9,
    type: TypeCard.hearth,
    img: "assets/cards/hearts_9.svg",
  },
  {
    id: 15,
    rank: 9,
    type: TypeCard.clubs,
    img: "assets/cards/clubs_9.svg",
  },
  {
    id: 16,
    rank: 9,
    type: TypeCard.spades,
    img: "assets/cards/spades_9.svg",
  },
  {
    id: 17,
    rank: 10,
    type: TypeCard.diamonds,
    img: "assets/cards/diamonds_10.svg",
  },
  {
    id: 18,
    rank: 10,
    type: TypeCard.hearth,
    img: "assets/cards/hearts_10.svg",
  },
  {
    id: 19,
    rank: 10,
    type: TypeCard.clubs,
    img: "assets/cards/clubs_10.svg",
  },
  {
    id: 20,
    rank: 10,
    type: TypeCard.spades,
    img: "assets/cards/spades_10.svg",
  },
  {
    id: 21,
    rank: 11,
    type: TypeCard.diamonds,
    img: "assets/cards/diamonds_jack.svg",
  },
  {
    id: 22,
    rank: 11,
    type: TypeCard.hearth,
    img: "assets/cards/hearts_jack.svg",
  },
  {
    id: 23,
    rank: 11,
    type: TypeCard.clubs,
    img: "assets/cards/clubs_jack.svg",
  },
  {
    id: 24,
    rank: 11,
    type: TypeCard.spades,
    img: "assets/cards/spades_jack.svg",
  },
  {
    id: 25,
    rank: 12,
    type: TypeCard.diamonds,
    img: "assets/cards/diamonds_queen.svg",
  },
  {
    id: 26,
    rank: 12,
    type: TypeCard.hearth,
    img: "assets/cards/hearts_queen.svg",
  },
  {
    id: 27,
    rank: 12,
    type: TypeCard.clubs,
    img: "assets/cards/clubs_queen.svg",
  },
  {
    id: 28,
    rank: 12,
    type: TypeCard.spades,
    img: "assets/cards/spades_queen.svg",
  },
  {
    id: 29,
    rank: 13,
    type: TypeCard.diamonds,
    img: "assets/cards/diamonds_king.svg",
  },
  {
    id: 30,
    rank: 13,
    type: TypeCard.hearth,
    img: "assets/cards/hearts_king.svg",
  },
  {
    id: 31,
    rank: 13,
    type: TypeCard.clubs,
    img: "assets/cards/clubs_king.svg",
  },
  {
    id: 32,
    rank: 13,
    type: TypeCard.spades,
    img: "assets/cards/spades_king.svg",
  },
  {
    id: 33,
    rank: 14,
    type: TypeCard.diamonds,
    img: "assets/cards/diamonds_ace.svg",
  },
  {
    id: 34,
    rank: 14,
    type: TypeCard.hearth,
    img: "assets/cards/hearts_ace.svg",
  },
  {
    id: 35,
    rank: 14,
    type: TypeCard.clubs,
    img: "assets/cards/clubs_ace.svg",
  },
  {
    id: 36,
    rank: 14,
    type: TypeCard.spades,
    img: "assets/cards/spades_ace.svg",
  },
];
